// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SkillTreeRazorPageBlogSample.Models
{
    public partial class Article
    {
        public Guid Id { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string CoverPhoto { get; set; }
        public DateTime CreateDate { get; set; }
        public string Tags { get; set; }
    }
}